import { test } from '@playwright/test'

test.describe('modal screenshots', () => {
  test('picker dark', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(600)
    await page.screenshot({ path: 'modal-iter-1-picker-dark.png' })
  })

  test('picker light', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.evaluate(() => {
      document.documentElement.classList.remove('dark')
    })
    await page.waitForTimeout(200)
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(600)
    await page.screenshot({ path: 'modal-iter-1-picker-light.png' })
  })

  test('auth stripe dark', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(500)
    await page.screenshot({ path: 'modal-iter-2-auth-dark.png' })
  })

  test('auth stripe light', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.evaluate(() => { document.documentElement.classList.remove('dark') })
    await page.waitForTimeout(200)
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(500)
    await page.screenshot({ path: 'modal-iter-2-auth-light.png' })
  })

  test('bridge dark', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(500)
    await page.screenshot({ path: 'modal-iter-3-bridge-dark.png' })
  })

  test('trust dark', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Approve →' }).click()
    await page.waitForTimeout(600)
    await page.screenshot({ path: 'modal-iter-4-trust-dark.png' })
  })

  test('trust light', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.evaluate(() => { document.documentElement.classList.remove('dark') })
    await page.waitForTimeout(200)
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Approve →' }).click()
    await page.waitForTimeout(600)
    await page.screenshot({ path: 'modal-iter-4-trust-light.png' })
  })

  test('discover dark', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Approve →' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /continue/i }).click()
    await page.waitForTimeout(600)
    await page.screenshot({ path: 'modal-iter-5-discover-dark.png' })
  })

  test('confirm dark', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Approve →' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /continue/i }).click()
    // Wait for discovery to complete (~3.6s for stripe)
    await page.waitForTimeout(4500)
    await page.screenshot({ path: 'modal-iter-6-confirm-dark.png' })
  })

  test('confirm light', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.evaluate(() => { document.documentElement.classList.remove('dark') })
    await page.waitForTimeout(200)
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Approve →' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /continue/i }).click()
    await page.waitForTimeout(4500)
    await page.screenshot({ path: 'modal-iter-6-confirm-light.png' })
  })

  test('auth s3 form dark', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Amazon S3' }).click()
    await page.waitForTimeout(500)
    await page.screenshot({ path: 'modal-iter-2b-auth-s3-dark.png' })
  })

  test('auth s3 form light', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.evaluate(() => { document.documentElement.classList.remove('dark') })
    await page.waitForTimeout(200)
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Amazon S3' }).click()
    await page.waitForTimeout(500)
    await page.screenshot({ path: 'modal-iter-2b-auth-s3-light.png' })
  })

  test('bridge light', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.evaluate(() => { document.documentElement.classList.remove('dark') })
    await page.waitForTimeout(200)
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(500)
    await page.screenshot({ path: 'modal-iter-3-bridge-light.png' })
  })

  test('done dark', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Approve →' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /continue/i }).click()
    // Wait for discovery (~3.6s)
    await page.waitForTimeout(4500)
    // Click Connect Stripe
    await page.getByRole('button', { name: /connect stripe/i }).click()
    await page.waitForTimeout(1500)
    await page.screenshot({ path: 'modal-iter-7-done-dark.png' })
  })

  test('done light', async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto('/sources', { waitUntil: 'networkidle' })
    await page.evaluate(() => { document.documentElement.classList.remove('dark') })
    await page.waitForTimeout(200)
    await page.getByRole('button', { name: /connect a source/i }).first().click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Stripe' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /sign in with stripe/i }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: 'Approve →' }).click()
    await page.waitForTimeout(400)
    await page.getByRole('button', { name: /continue/i }).click()
    await page.waitForTimeout(4500)
    await page.getByRole('button', { name: /connect stripe/i }).click()
    await page.waitForTimeout(1500)
    await page.screenshot({ path: 'modal-iter-7-done-light.png' })
  })
})
